### ISSUE TITLE
Code snippet is truncated

### ISSUE THREAD

**Issue by homersimpsons** [exercism/arturo#119]
On https://exercism.org/tracks/arturo the code snippet is truncated:
![image](https://github.com/user-attachments/assets/2510ac1e-11ff-47be-a113-0cf8c10ecdc1)

**Comment by drkameleon** [comment]
> On https://exercism.org/tracks/arturo the code snippet is truncated: 

Well spotted! 😉 
I had noticed that too initially but wasn't sure it wasn't just me... or sth to do with the browser window's size.

**Comment by BNAndras** [comment]
I ccould remove some of the characters or do we want to use a different snippet showing Arturo in 10 lines or less? https://exercism.org/docs/building/tracks/docs#h-file-snippet-txt

**Comment by drkameleon** [comment]
> I ccould remove some of the characters or do we want to use a different snippet showing Arturo in 10 lines or less? https://exercism.org/docs/building/tracks/docs#h-file-snippet-txt

Interesting. 🤔 

Could the snippet from our current header (@ https://arturo-lang.io) work? I did my best to keep it short and to-the-point while highlighting as much of the "general idea" as possible...

**Comment by BNAndras** [comment]
Sure. If either of you want to update https://github.com/exercism/arturo/blob/main/docs/SNIPPET.txt, go ahead. Otherwise, I'll take care of it today or tomorrow.

**Comment by drkameleon** [comment]
> Sure. If either of you want to update https://github.com/exercism/arturo/blob/main/docs/SNIPPET.txt, go ahead. Otherwise, I'll take care of it today or tomorrow.

Just opened a PR 😉

**Comment by BNAndras** [comment]
![image](https://github.com/user-attachments/assets/01971f02-c26e-4940-8a32-ef381d3342dd)

Looks good to me on the site

**Comment by drkameleon** [comment]
Awesome! :)
