### ISSUE TITLE
Update repo tags

### ISSUE THREAD

**Issue by BNAndras** [exercism/arturo#128]
@ErikSchierboom, can we update the repo tags whenever you have time? No rush.

Remove `wip-track` and add `arturo` and `community-contributions-accepted`. I'm assuming `maintained-autonomous` will be automatically added when we next update maintainership status across all tracks. If not, we should add that too.

**Comment by BNAndras** [comment]
Oh and `exercism-track` as well. Thanks :)

**Comment by ErikSchierboom** [comment]
Done
