### ISSUE TITLE
Update `bin/install-arturo`

### ISSUE THREAD

**Issue by BNAndras** [exercism/arturo#97]
https://github.com/exercism/arturo/blob/main/bin/install-arturo currently downloads the Linux build for MacOS systems (below). The script should check which operating system is installed, bailing with a message if it's MacOS (no full build). For Linux systems, it should grab the Linux build and for Windows systems, the Windows build.

```bash
file ~/.arturo/bin/arturo
/Users/anagy/.arturo/bin/arturo: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=814a41f9a784138f45f9001a28d2af05a9185192, for GNU/Linux 3.2.0, not stripped
```

**Comment by ErikSchierboom** [comment]
We _could_ use the `exercism/arturo-test-runner` Docker image for macOS, as that does work, even on ARM-based macs.

**Comment by BNAndras** [comment]
It seems the team is pretty close to having a working Arturo download script for nightlies. That'd simplify things for us.
